In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [16]:
model = load_model('model.h5')


with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

with open('label_encoder.pkl', 'rb') as f:
    label_encoder = pickle.load(f)

with open('one_hot_encoder.pkl', 'rb') as f:
    one_hot_encoder = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [6]:
input_data={
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [17]:
geo_encoded=one_hot_encoder.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns=one_hot_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\Lakshya\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [18]:
input_data = pd.DataFrame([input_data])

In [20]:
input_data = pd.concat([input_data, geo_encoded_df], axis=1).drop(columns=['Geography'],axis=1)

In [21]:
input_data

   CreditScore Gender  ...  Geography_Germany  Geography_Spain
0          600   Male  ...                0.0              0.0

[1 rows x 12 columns]

In [29]:
print(label_encoder.classes_)

[0 1]

In [31]:
input_data['Gender']=1

In [32]:
input_data

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [33]:
scaler_input=   scaler.transform(input_data)

In [34]:
model.predict(scaler_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 375ms/step

array([[0.07847126]], dtype=float32)

In [35]:
predictionProbability=model.predict(scaler_input)[0][0]
if(predictionProbability>0.5):
    print(f"The customer is likely to churn with a probability of {predictionProbability:.2f}")
else:
    print(f"The customer is unlikely to churn with a probability of {predictionProbability:.2f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
The customer is unlikely to churn with a probability of 0.08